-- MySQL Script generated by MySQL Workbench
-- Tue May 26 01:29:05 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HumanData_RH_Solutions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HumanData_RH_Solutions` DEFAULT CHARACTER SET utf8 ;
USE `HumanData_RH_Solutions` ;

-- ============================================================
-- MÓDULO 1 — DOMÍNIO (LOOKUP TABLES)
-- Finalidade geral: alimentar campos de múltipla escolha das
-- entidades do sistema, garantindo RNF04 e 3NF.
-- Em vez de ENUM espalhado pelo código, cada conjunto de opções
-- fixas vive em sua própria tabela; alterações futuras não
-- exigem ALTER TABLE na entidade principal.
-- ============================================================

-- ------------------------------------------------------------
-- Tabela: sexo
-- Finalidade: Controlar as opções de sexo biológico /
--             identificação do colaborador.
-- Carga inicial: Masculino, Feminino, Outro,
--                Prefiro não informar, Não binário.
-- NF aplicada: 1NF (valor atômico por célula);
--              3NF (nenhuma dependência transitiva).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Sexo` (
  `idSexo` TINYINT NOT NULL AUTO_INCREMENT, -- PK — identificador único da opção de sexo
  `Desc_Sexo` VARCHAR(20) NOT NULL, -- Rótulo da opção (ex: Masculino, Feminino)
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;
-- Domínio: opções de sexo / identificação de gênero do colaborador


-- ------------------------------------------------------------
-- Tabela: estado_civil
-- Finalidade: Opções de estado civil para fins de benefícios
--             e obrigações trabalhistas.
-- Carga inicial: Solteiro(a), Casado(a), Divorciado(a),
--                Viúvo(a), União Estável.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`EstadoCivil` (
  `idEstadoCivil` TINYINT NOT NULL AUTO_INCREMENT, -- PK — identificador único do estado civil
  `Desc_EstadoCivil` VARCHAR(50) NOT NULL, -- Rótulo do estado civil (ex: Casado(a))
  PRIMARY KEY (`idEstadoCivil`))
ENGINE = InnoDB;
-- Domínio: estados civis válidos para o cadastro do colaborador


-- ------------------------------------------------------------
-- Tabela: tipo_contrato
-- Finalidade: Definir a modalidade de contratação da pessoa.
-- Carga inicial: CLT, PJ, Estagiário, Temporário, Aprendiz.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`TipodeContrato` (
  `idTipoContrato` TINYINT NOT NULL AUTO_INCREMENT, -- PK — identificador único do tipo de contrato
  `Desc_TipoContrato` VARCHAR(50) NOT NULL, -- Modalidade de contrato (ex: CLT, PJ, Estagiário)
  PRIMARY KEY (`idTipoContrato`))
ENGINE = InnoDB;
-- Domínio: modalidades de contratação de trabalho permitidas


-- ------------------------------------------------------------
-- Tabela: tipo_ocorrencia
-- Finalidade: Classificar eventos disciplinares ou de mérito.
-- Carga inicial: Advertência Verbal, Advertência Escrita,
--                Suspensão, Elogio Formal, Punição Disciplinar.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`TipoOcorrencia` (
  `idTipoOcorrencia` TINYINT NOT NULL AUTO_INCREMENT, -- PK — identificador único do tipo de ocorrência
  `Desc_Ocorrências` VARCHAR(50) NOT NULL, -- Classificação do evento (ex: Advertência Verbal, Elogio Formal)
  PRIMARY KEY (`idTipoOcorrencia`))
ENGINE = InnoDB;
-- Domínio: tipos de ocorrência disciplinar ou de reconhecimento


-- ------------------------------------------------------------
-- Tabela: motivo_desligamento
-- Finalidade: Categorizar o encerramento do vínculo de trabalho.
-- Carga inicial: Pedido de demissão, Demissão sem justa causa,
--                Demissão com justa causa, Aposentadoria,
--                Término de contrato.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`MotivoDesligamento` (
  `idMotivo` TINYINT NOT NULL AUTO_INCREMENT, -- PK — identificador único do motivo de desligamento
  `Desc_Desligamento` VARCHAR(50) NOT NULL, -- Descrição do motivo (ex: Pedido de demissão, Aposentadoria)
  PRIMARY KEY (`idMotivo`))
ENGINE = InnoDB;
-- Domínio: motivos de encerramento do vínculo empregatício


-- ------------------------------------------------------------
-- Tabela: status_vaga
-- Finalidade: Controlar as fases de um processo de recrutamento.
-- Carga inicial: Aberta, Em andamento, Encerrada,
--                Cancelada, Em aprovação.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`StatusdeVagas` (
  `idStatusVagas` TINYINT NOT NULL AUTO_INCREMENT, -- PK — identificador único do status da vaga
  `Desc_StatusVagas` VARCHAR(50) NOT NULL, -- Fase do processo seletivo (ex: Aberta, Encerrada)
  PRIMARY KEY (`idStatusVagas`))
ENGINE = InnoDB;
-- Domínio: fases / status do processo de recrutamento e seleção


-- ============================================================
-- MÓDULO 2 — ESTRUTURA ORGANIZACIONAL
-- Mapeia a árvore de departamentos e o catálogo de posições.
-- ============================================================

-- ------------------------------------------------------------
-- Tabela: departamento
-- Finalidade: Mapear o organograma corporativo (RF03).
--             Auto-relacionamento via id_depto_superior para
--             representar hierarquia entre setores.
--             NULL em id_depto_superior = topo da hierarquia.
-- NF: 3NF — id_depto_superior depende apenas da PK.
-- RNF01: ON DELETE RESTRICT impede exclusão de depto com filhos
--        ou com colaboradores vinculados.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do departamento
  `id_Depto_Superior` INT NOT NULL, -- FK auto-referência — departamento pai na hierarquia
  `Nome` VARCHAR(100) NOT NULL, -- Nome completo do departamento (ex: Recursos Humanos)
  `Sigla` VARCHAR(10) NOT NULL, -- Sigla de referência do departamento (ex: RH, TI, FIN)
  PRIMARY KEY (`idDepartamento`),
  INDEX `fk_Departamento_Departamento1_idx` (`id_Depto_Superior` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_Departamento1`
    FOREIGN KEY (`id_Depto_Superior`)
    REFERENCES `HumanData_RH_Solutions`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF03 — Organograma: departamentos e hierarquia entre eles

-- ------------------------------------------------------------
-- Tabela: cargo
-- Finalidade: Cadastrar os requisitos mínimos e a remuneração
--             referencial das funções (RF02).
-- NF: 2NF — todos os atributos dependem exclusivamente da PK
--            id_cargo; 3NF — sem dependências transitivas.
-- RNF01: colaboradores vinculados a um cargo impedem sua
--        exclusão (FK em colaborador com ON DELETE RESTRICT).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do cargo
  `Titulo` VARCHAR(100) NOT NULL, -- Título/nome do cargo (ex: Analista de RH Pleno)
  `Descricao` TEXT NOT NULL, -- Descrição das responsabilidades e atribuições do cargo
  `Requisito` TEXT NOT NULL, -- Requisitos mínimos: escolaridade, certificações, experiência
  `Salario_Base` DECIMAL(10,2) NOT NULL, -- Salário base de referência salarial para o cargo — campo sensível (RNF02)
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;
-- RF02 — Catálogo de cargos com requisitos e remuneração referencial

-- ============================================================
-- MÓDULO 3 — COLABORADOR E CONTATOS (ENTIDADE CENTRAL)
-- Para cumprir rigorosamente a 1NF, todos os atributos
-- multivalorados (telefones, endereços) foram extraídos
-- para tabelas satélites dedicadas.
-- ============================================================

-- ------------------------------------------------------------
-- Tabela: colaborador
-- Finalidade: Cadastro mestre do trabalhador ativo ou inativo
--             (RF01). Ponto central de relacionamento do sistema.
-- NF: 1NF — cada coluna contém um único valor atômico;
--     2NF — todos os atributos dependem só da PK;
--     3NF — sem dependências transitivas entre colunas.
-- RNF02: cpf, rg, pis, salario são campos sensíveis —
--        restringir via Roles/Permissions no ambiente de produção.
-- RNF03: índice explícito em nome; CPF tem índice implícito
--        pelo UNIQUE.
-- RNF01: FKs de cargo e departamento usam ON DELETE RESTRICT.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Colaborador` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do colaborador no sistema
  `Departamento_idDepartamento` INT NOT NULL, -- FK — departamento atual do colaborador
  `Sexo_idSexo` TINYINT NOT NULL, -- FK — referência ao domínio sexo
  `EstadoCivil_idEstadoCivil` TINYINT NOT NULL, -- FK — referência ao domínio estado_civil
  `Cargo_idCargo` INT NOT NULL, -- FK — cargo atual do colaborador
  `TipodeContrato_idTipoContrato` TINYINT NOT NULL, -- FK — modalidade de contrato (CLT, PJ, etc.)
  `Nome` VARCHAR(150) NOT NULL, -- Nome completo do colaborador
  `CPF` CHAR(11) NOT NULL, -- CPF sem formatação (11 dígitos) — SENSÍVEL (RNF02)
  `RG` VARCHAR(20) NOT NULL, -- RG do colaborador — SENSÍVEL (RNF02)
  `Data_Nascimento` DATE NOT NULL,
  `Data_Admissao` DATE NOT NULL, -- Data de admissão — usada para tempo de casa (RF15)
  `Salario` DECIMAL(10,2) NOT NULL, -- Salário atual do colaborador — SENSÍVEL (RNF02)
  `Status_Colaborador` BIT(1) NOT NULL DEFAULT 1 COMMENT '0 = desligado\n1 = ativo', -- Flag de status
  PRIMARY KEY (`idColaborador`),
  INDEX `fk_Colaborador_Sexo1_idx` (`Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Colaborador_Estado Civil1_idx` (`EstadoCivil_idEstadoCivil` ASC) VISIBLE,
  INDEX `fk_Colaborador_Tipo de Contrato1_idx` (`TipodeContrato_idTipoContrato` ASC) VISIBLE,
  INDEX `fk_Colaborador_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_Colaborador_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Colaborador_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `HumanData_RH_Solutions`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Estado Civil1`
    FOREIGN KEY (`EstadoCivil_idEstadoCivil`)
    REFERENCES `HumanData_RH_Solutions`.`EstadoCivil` (`idEstadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Tipo de Contrato1`
    FOREIGN KEY (`TipodeContrato_idTipoContrato`)
    REFERENCES `HumanData_RH_Solutions`.`TipodeContrato` (`idTipoContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `HumanData_RH_Solutions`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `HumanData_RH_Solutions`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF01 — Cadastro mestre dos colaboradores: dados pessoais e vínculo empregatício


-- ------------------------------------------------------------
-- Tabela: colaborador_telefone
-- Finalidade: Armazenar múltiplos contatos telefônicos por
--             funcionário. Criada exclusivamente para garantir
--             a 1NF — um colaborador pode ter vários números,
--             mas cada linha desta tabela contém apenas um.
-- ON DELETE CASCADE: ao excluir o colaborador, seus telefones
-- são removidos automaticamente (dados satélite).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`ColaboradorTelefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do telefone
  `Colaborador_idColaborador` INT NOT NULL, -- FK — colaborador dono deste telefone
  `Tipo` VARCHAR(20) NOT NULL COMMENT '-- Ex: Celular, Residencial, Comercial', -- Classificação do telefone: Celular, Residencial ou Comercial
  `Numero` VARCHAR(20) NOT NULL, -- Número com DDD, sem formatação (ex: 61991234567)
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_ColaboradorTelefone_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_ColaboradorTelefone_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF01 / 1NF — Telefones do colaborador em tabela satélite (multivalorado separado)


-- ------------------------------------------------------------
-- Tabela: colaborador_endereco
-- Finalidade: Armazenar o local de residência isolado da
--             entidade principal — conformidade com 1NF e 2NF.
--             A coluna "principal" identifica o endereço de
--             correspondência ativo quando há mais de um.
-- ON DELETE CASCADE: endereços são dados satélite do colaborador.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`ColaboradorEndereço` (
  `idEndereço` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do endereço
  `Colaborador_idColaborador` INT NOT NULL, -- FK — colaborador dono deste endereço
  `Logradouro` VARCHAR(200) NOT NULL, -- Tipo e nome da via (ex: Rua das Acácias, Av. W3 Norte
  `Numero` VARCHAR(10) NULL, -- Número do imóvel no logradouro
  `Complemento` VARCHAR(100) NULL, -- Complemento opcional: Apto, Bloco, Casa, etc.
  `Bairro` VARCHAR(100) NULL, -- Bairro do endereço
  `Cidade` VARCHAR(100) NOT NULL, -- Município do endereço
  `UF` CHAR(2) NOT NULL, -- Sigla da Unidade Federativa (ex: DF, SP, RJ)
  `CEP` CHAR(8) NOT NULL, -- CEP sem formatação — apenas 8 dígitos
  `Principal` BIT(1) NULL DEFAULT 1 COMMENT '0 = Não é principal\n1 = principal', -- Indica o endereço de correspondência ativo
  PRIMARY KEY (`idEndereço`),
  INDEX `fk_ColaboradorEndereço_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_ColaboradorEndereço_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF01 / 1NF — Endereços do colaborador em tabela satélite (multivalorado separado)


-- ============================================================
-- MÓDULO 4 — HISTÓRICO E MOVIMENTAÇÃO
-- ============================================================

-- ------------------------------------------------------------
-- Tabela: historico_alocacao
-- Finalidade: Registrar a trilha de auditoria sobre todas as
--             alterações de cargo ou setor ao longo do tempo
--             (RF04). data_fim NULL indica alocação vigente.
-- NF: 3NF — cada coluna depende unicamente da PK.
-- RNF01: ON DELETE RESTRICT em cargo e departamento impede
--        exclusão de registros referenciados no histórico.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`HistoricoAlocacao` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do registro de movimentação
  `Colaborador_idColaborador` INT NOT NULL, -- FK — colaborador que sofreu a movimentação
  `Cargo_idCargo` INT NOT NULL, -- FK — cargo assumido nesta alocação
  `Departamento_idDepartamento` INT NOT NULL, -- FK — departamento desta alocação
  `Data_Inicio` DATE NOT NULL, -- Data de início da alocação neste cargo / departamento
  `Data_Fim` DATE NULL COMMENT '-- NULL = posição atual', -- Data de encerramento da alocação; NULL = vigente
  `Observacao` TEXT NULL, -- Motivo ou observação sobre a movimentação (ex: promoção, transferência)
  PRIMARY KEY (`idHistorico`),
  INDEX `fk_HistoricoAlocacao_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  INDEX `fk_HistoricoAlocacao_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_HistoricoAlocacao_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_HistoricoAlocacao_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistoricoAlocacao_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `HumanData_RH_Solutions`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistoricoAlocacao_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `HumanData_RH_Solutions`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF04 — Trilha de auditoria das movimentações de cargo e departamento do colaborador


-- ============================================================
-- MÓDULO 5 — OPERAÇÕES E DEPARTAMENTO PESSOAL
-- ============================================================

-- ------------------------------------------------------------
-- Tabela: registro_ponto
-- Finalidade: Capturar as batidas de ponto eletrônico diárias,
--             atrasos e justificativas (RF05).
-- NF: 1NF — um registro por evento (entrada ou saída).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`RegistroPonto` (
  `idPonto` INT UNSIGNED NOT NULL AUTO_INCREMENT, -- PK — identificador único da batida de ponto
  `Colaborador_idColaborador` INT NOT NULL, -- FK — colaborador que realizou a batida
  `Data_Hora` DATETIME NOT NULL, -- Data e hora exata do evento de ponto
  `Tipo` VARCHAR(20) NOT NULL COMMENT '-- Ex: Entrada, Saída, Intervalo', -- Tipo do evento: Entrada, Saída, Intervalo Início, Intervalo Fim
  `Justificativa` TEXT NULL, -- Justificativa de falta ou atraso quando aplicável
  PRIMARY KEY (`idPonto`),
  INDEX `fk_RegistroPonto_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_RegistroPonto_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF05 — Registros de ponto eletrônico: entradas, saídas e justificativas


-- ------------------------------------------------------------
-- Tabela: folha_pagamento
-- Finalidade: Arquivar de forma imutável os demonstrativos
--             financeiros gerados mês a mês (RF06, RF14).
--             A combinação (id_colaborador, ano, mês) é única —
--             não existe duas folhas do mesmo colaborador
--             no mesmo período.
-- NF: 2NF e 3NF — todos os valores dependem da PK;
--     salario_liquido, embora derivável, é armazenado para
--     garantir o histórico imutável do demonstrativo.
-- RNF02: salario_bruto e salario_liquido são campos sensíveis.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`FolhaPagamento` (
  `idFolha` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do demonstrativo de folha
  `Colaborador_idColaborador` INT NOT NULL, -- FK — colaborador ao qual o demonstrativo pertence
  `Competencia_Ano` YEAR NOT NULL, -- Ano de referência da competência (ex: 2025)
  `Competencia_Mes` TINYINT NOT NULL, -- Mês de referência da competência (1 a 12)
  `Salario_Bruto` DECIMAL(10,2) NOT NULL, -- Salário bruto do período — SENSÍVEL (RNF02)
  `Desconto_INSS` DECIMAL(10,2) NOT NULL, -- Desconto previdenciário (INSS) calculado no período
  `Desconto_FGTS` DECIMAL(10,2) NOT NULL, -- FGTS recolhido pelo empregador (8% do bruto)
  `Desconto_IRRF` DECIMAL(10,2) NOT NULL, -- Imposto de Renda Retido na Fonte (tabela progressiva)
  `Outros_Descontos` DECIMAL(10,2) NULL DEFAULT 0.00, -- Outros descontos: faltas, adiantamento, coparticipação de benefícios
  `Salario_Liquido` DECIMAL(10,2) NOT NULL, -- Valor líquido a receber = bruto - total de descontos — SENSÍVEL (RNF02)
  `Data_Pagamento` DATE NOT NULL, -- Data em que o pagamento foi efetivado
  PRIMARY KEY (`idFolha`),
  INDEX `fk_FolhaPagamento_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_FolhaPagamento_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF06 / RF14 — Demonstrativo financeiro mensal imutável por colaborador


-- ------------------------------------------------------------
-- Tabela: ferias
-- Finalidade: Controlar os períodos aquisitivos e de gozo
--             do descanso remunerado (RF07).
--             data_inicio_gozo NULL = férias ainda não agendadas.
-- NF: 3NF — data_fim_aquisitivo depende apenas da PK.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Ferias` (
  `idFerias` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do registro de férias
  `Colaborador_idColaborador` INT NOT NULL, -- FK — colaborador titular das férias
  `Data_Inicio_Aquisitivo` DATE NOT NULL, -- Início do período aquisitivo (12 meses trabalhados contínuos)
  `Data_Fim_Aquisitivo` DATE NOT NULL, -- Fim do período aquisitivo — prazo limite para gozar
  `Saldo_dias` TINYINT NOT NULL, -- Total de dias disponíveis para gozo (normalmente 30)
  `Data_Inicio_Ferias` DATE NULL, -- Data de início do período de descanso; NULL = não agendado
  `Data_Fim_Ferias` DATE NULL, -- Data de fim do período de descanso
  `Dias_Ferias` TINYINT NULL, -- Quantidade de dias efetivamente de ferias
  PRIMARY KEY (`idFerias`),
  INDEX `fk_Ferias_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_Ferias_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF07 — Controle de férias: saldo, período aquisitivo e agendamento de gozo


-- ============================================================
-- MÓDULO 6 — BENEFÍCIOS (RELACIONAMENTO N:M)
-- ============================================================

-- ------------------------------------------------------------
-- Tabela: beneficio
-- Finalidade: Catálogo de pacotes de benefícios oferecidos
--             pela empresa (VT, VR, Planos) (RF08).
-- NF: 2NF — todos os atributos dependem da PK id_beneficio.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Beneficio` (
  `idBeneficio` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do benefício
  `Nome` VARCHAR(100) NOT NULL, -- Nome do benefício (ex: Vale Transporte, Plano de Saúde)
  `Descricao` TEXT NULL, -- Descrição detalhada da cobertura ou funcionamento do benefício
  `Valor_Padrao` DECIMAL(10,2) NOT NULL, -- Valor padrão do benefício; pode ser sobreposto por valor_individual
  PRIMARY KEY (`idBeneficio`))
ENGINE = InnoDB;
-- RF08 — Catálogo de benefícios corporativos disponíveis para os colaboradores


-- ------------------------------------------------------------
-- Tabela: colaborador_beneficio
-- Finalidade: Tabela de junção / associativa que resolve o
--             relacionamento N:M entre Colaborador e Benefício.
--             valor_individual sobrepõe o padrão nos casos de
--             coparticipação ou acordos individuais (RF08).
-- NF: 2NF — valor_individual e data_inicio dependem do par
--     (id_colaborador, id_beneficio), que forma a PK composta.
-- Escopo (conforme documento): PK composta sem surrogate key.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`ColaboradorBeneficio` (
  `Beneficio_idBeneficio` INT NOT NULL, -- FK / PK — colaborador que recebe o benefício
  `Colaborador_idColaborador` INT NOT NULL, -- FK / PK — benefício concedido ao colaborador
  `Valor_Individual` DECIMAL(10,2) NULL, -- Valor negociado individualmente; sobrepõe o valor_padrao do catálogo
  `Data_Inicio` DATE NOT NULL, -- Data de início da concessão deste benefício ao colaborador
  `Data_Fim` DATE NULL COMMENT '-- NULL = benefício ativo', -- Data de encerramento da concessão; NULL = ainda ativo
  PRIMARY KEY (`Beneficio_idBeneficio`, `Colaborador_idColaborador`),
  INDEX `fk_Beneficio_has_Colaborador_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  INDEX `fk_Beneficio_has_Colaborador_Beneficio1_idx` (`Beneficio_idBeneficio` ASC) VISIBLE,
  CONSTRAINT `fk_Beneficio_has_Colaborador_Beneficio1`
    FOREIGN KEY (`Beneficio_idBeneficio`)
    REFERENCES `HumanData_RH_Solutions`.`Beneficio` (`idBeneficio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Beneficio_has_Colaborador_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF08 — Tabela associativa N:M: vincula colaboradores aos seus benefícios com valor individual


-- ============================================================
-- MÓDULO 7 — ESTRATÉGICO, DESENVOLVIMENTO E RECRUTAMENTO
-- ============================================================

-- ------------------------------------------------------------
-- Tabela: desligamento
-- Finalidade: Processar as rescisões contratuais e cálculos
--             financeiros finais (RF10).
--             UNIQUE em id_colaborador: um colaborador só pode
--             ter um registro de desligamento.
-- NF: 3NF — cada coluna de valor depende apenas da PK.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Desligamento` (
  `idDesligamento` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único do processo de desligamento
  `Colaborador_idColaborador` INT NOT NULL, -- FK — colaborador desligado (único por colaborador)
  `MotivoDesligamento_idMotivo` TINYINT NOT NULL, -- FK — motivo do encerramento do contrato (domínio)
  `Data_Desligamento` DATE NOT NULL, -- Data efetiva do desligamento
  `Saldo_Salario` DECIMAL(10,2) NULL, -- Saldo de salário proporcional aos dias trabalhados no mês
  `Ferias_Proporcionais` DECIMAL(10,2) NULL, -- Férias proporcionais ao período aquisitivo em aberto
  `Decimo_Terceiro` DECIMAL(10,2) NULL, -- Valor proporcional do 13º salário até a data do desligamento
  `FGTS_Rescisorio` DECIMAL(10,2) NULL, -- Saldo do FGTS a ser liberado ao colaborador
  `Multa_FGTS` DECIMAL(10,2) NULL, -- Multa de 40% sobre o FGTS (devida em demissão sem justa causa)
  `Total_Rescisao` DECIMAL(10,2) NULL, -- Valor total líquido da rescisão a ser pago ao colaborador
  `Observacao` TEXT NULL, -- Observações adicionais sobre o processo rescisório
  PRIMARY KEY (`idDesligamento`),
  INDEX `fk_Desligamento_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  INDEX `fk_Desligamento_MotivoDesligamento1_idx` (`MotivoDesligamento_idMotivo` ASC) VISIBLE,
  CONSTRAINT `fk_Desligamento_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Desligamento_MotivoDesligamento1`
    FOREIGN KEY (`MotivoDesligamento_idMotivo`)
    REFERENCES `HumanData_RH_Solutions`.`MotivoDesligamento` (`idMotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF10 — Desligamento e rescisão: cálculos financeiros finais do encerramento contratual


-- ------------------------------------------------------------
-- Tabela: ocorrencia
-- Finalidade: Anotar advertências, suspensões ou elogios
--             formais (RF09). A coluna id_gestor referencia
--             a própria tabela colaborador para auditar quem
--             registrou o evento — auto-referência de auditoria.
-- NF: 3NF — cada coluna depende exclusivamente da PK.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Ocorrencia` (
  `idOcorrencia` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único da ocorrência
  `Colaborador_idColaborador` INT NOT NULL, -- FK — colaborador a quem a ocorrência se refere
  `TipoOcorrencia_idTipoOcorrencia` TINYINT NOT NULL, -- FK — classificação da ocorrência (domínio tipo_ocorrencia)
  `idGestor` INT NOT NULL, -- FK — colaborador (gestor) que registrou / aplicou a ocorrência (trilha de auditoria)
  `Data_Ocorrencia` DATE NOT NULL, -- Data em que o fato ocorreu ou foi registrado
  `Descricao` TEXT NULL, -- Relato detalhado do fato que motivou o registro da ocorrência
  PRIMARY KEY (`idOcorrencia`),
  INDEX `fk_Ocorrencia_Colaborador1_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  INDEX `fk_Ocorrencia_TipoOcorrencia1_idx` (`TipoOcorrencia_idTipoOcorrencia` ASC) VISIBLE,
  INDEX `fk_Ocorrencia_Colaborador2_idx` (`idGestor` ASC) VISIBLE,
  CONSTRAINT `fk_Ocorrencia_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocorrencia_TipoOcorrencia1`
    FOREIGN KEY (`TipoOcorrencia_idTipoOcorrencia`)
    REFERENCES `HumanData_RH_Solutions`.`TipoOcorrencia` (`idTipoOcorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocorrencia_Colaborador2`
    FOREIGN KEY (`idGestor`)
    REFERENCES `HumanData_RH_Solutions`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF09 — Registro de ocorrências disciplinares e de reconhecimento com trilha de auditoria


-- ------------------------------------------------------------
-- Tabela: vaga
-- Finalidade: Armazenar os processos de recrutamento abertos
--             para vagas internas ou externas (RF13).
-- NF: 3NF — data_encerramento depende apenas da PK.
-- RNF01: ON DELETE RESTRICT em cargo, departamento e status.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HumanData_RH_Solutions`.`Vaga` (
  `idVaga` INT NOT NULL AUTO_INCREMENT, -- PK — identificador único da vaga
  `Cargo_idCargo` INT NOT NULL, -- FK — cargo ao qual a vaga se refere
  `Departamento_idDepartamento` INT NOT NULL, -- FK — departamento que abriu a vaga
  `StatusdeVagas_idStatusVagas` TINYINT NOT NULL, -- FK — fase atual do processo seletivo
  `Titulo` VARCHAR(120) NOT NULL, -- Título da vaga divulgado nas plataformas de recrutamento
  `Data_Abertura` DATE NOT NULL, -- Data de abertura oficial do processo seletivo
  `Data_Encerramento` DATE NULL, -- Data de encerramento do processo; NULL = processo ainda aberto
  `Tipo` VARCHAR(20) NULL COMMENT '-- Interna, Externa, Mista',
  PRIMARY KEY (`idVaga`),
  INDEX `fk_Vaga_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_Vaga_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  INDEX `fk_Vaga_Status de vagas1_idx` (`StatusdeVagas_idStatusVagas` ASC) VISIBLE,
  CONSTRAINT `fk_Vaga_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `HumanData_RH_Solutions`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaga_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `HumanData_RH_Solutions`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaga_Status de vagas1`
    FOREIGN KEY (`StatusdeVagas_idStatusVagas`)
    REFERENCES `HumanData_RH_Solutions`.`StatusdeVagas` (`idStatusVagas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- RF13 — Gestão de vagas: processos de recrutamento internos e externos


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- =============================================================
-- HumanData RH Solutions — Scripts DML
-- Inserts + Consultas SELECT
-- =============================================================

USE HumanData_RH_Solutions;

-- INSERTS

-- =========================
-- TABELA: Sexo
-- =========================
INSERT INTO Sexo (Desc_Sexo) VALUES
('Masculino'),
('Feminino'),
('Não Binário'),
('Outro'),
('Prefiro não informar');

-- =========================
-- TABELA: EstadoCivil
-- =========================
INSERT INTO EstadoCivil (Desc_EstadoCivil) VALUES
('Solteiro(a)'),
('Casado(a)'),
('Divorciado(a)'),
('Viúvo(a)'),
('União Estável');

-- =========================
-- TABELA: TipodeContrato
-- =========================
INSERT INTO TipodeContrato (Desc_TipoContrato) VALUES
('CLT'),
('PJ'),
('Estágio'),
('Temporário'),
('Aprendiz');

-- =========================
-- TABELA: TipoOcorrencia
-- =========================
INSERT INTO TipoOcorrencia (Desc_Ocorrências) VALUES
('Advertência Verbal'),
('Advertência Escrita'),
('Suspensão'),
('Elogio Formal'),
('Punição Disciplinar');

-- =========================
-- TABELA: MotivoDesligamento
-- =========================
INSERT INTO MotivoDesligamento (Desc_Desligamento) VALUES
('Pedido de demissão'),
('Demissão sem justa causa'),
('Demissão com justa causa'),
('Fim de contrato'),
('Aposentadoria');

-- =========================
-- TABELA: StatusdeVagas
-- =========================
INSERT INTO StatusdeVagas (Desc_StatusVagas) VALUES
('Aberta'),
('Em andamento'),
('Fechada'),
('Cancelada'),
('Pausada');

-- =========================
-- TABELA: Departamento
-- =========================
INSERT INTO Departamento (idDepartamento, id_Depto_Superior, Nome, Sigla) VALUES
  (1, 1, 'Diretoria Geral',         'DIR'),   -- topo da hierarquia: aponta para si mesmo
  (2, 1, 'Recursos Humanos',        'RH'),
  (3, 1, 'Tecnologia da Informação','TI'),
  (4, 1, 'Financeiro',              'FIN'),
  (5, 2, 'Recrutamento e Seleção',  'R&S');   -- filho do RH

-- =========================
-- TABELA: Cargo
-- =========================
INSERT INTO Cargo (Titulo, Descricao, Requisito, Salario_Base) VALUES
('Desenvolvedor Back-end', 'Responsável pelo servidor', 'Java e SQL', 5500.00),
('Analista de RH', 'Gestão de pessoas', 'Pacote Office', 4200.00),
('Analista Financeiro', 'Controle financeiro', 'Excel avançado', 4800.00),
('Designer', 'Criação visual', 'Photoshop', 3500.00),
('Suporte Técnico', 'Atendimento ao usuário', 'Redes básicas', 3000.00);

-- =========================
-- TABELA: Colaborador
-- =========================
INSERT INTO Colaborador
(Departamento_idDepartamento, Sexo_idSexo, EstadoCivil_idEstadoCivil, Cargo_idCargo, TipodeContrato_idTipoContrato, Nome, CPF, RG, Data_Nascimento, Data_Admissao, Salario, Status_Colaborador)
VALUES
(1,1,1,1,1,'João Silva','11111111111','MG123456','1998-04-10','2024-01-15',6000.00, 1),
(2,2,2,2,1,'Maria Souza','22222222222','DF223344','1995-07-21','2023-09-01',4500.00, 1),
(3,1,1,3,2,'Carlos Lima','33333333333','SP334455','1992-11-12','2022-03-10',5200.00, 1),
(4,2,3,4,3,'Ana Costa','44444444444','GO445566','2000-05-18','2025-01-20',3500.00, 1),
(5,1,1,5,1,'Pedro Alves','55555555555','RJ556677','1999-08-30','2021-06-11',3200.00, 1);

-- =========================
-- TABELA: ColaboradorTelefone
-- =========================
INSERT INTO ColaboradorTelefone (Colaborador_idColaborador, Tipo, Numero) VALUES
(1,'Celular','61999990001'),
(2,'Celular','61999990002'),
(3,'Residencial','6133334444'),
(4,'Comercial','6144445555'),
(5,'Celular','61999990005');

-- =========================
-- TABELA: ColaboradorEndereço
-- =========================
INSERT INTO ColaboradorEndereço
(Colaborador_idColaborador, Logradouro, Numero, Complemento, Bairro, Cidade, UF, CEP, Principal)
VALUES
(1,'Rua A','100','Casa','Centro','Brasília','DF','70000001',1),
(2,'Rua B','200','Apto 101','Asa Sul','Brasília','DF','70000002',1),
(3,'Rua C','300','Casa','Taguatinga','Brasília','DF','70000003',1),
(4,'Rua D','400','Bloco B','Guará','Brasília','DF','70000004',1),
(5,'Rua E','500','Casa','Ceilândia','Brasília','DF','70000005',1);

-- =========================
-- TABELA: HistoricoAlocacao
-- =========================
INSERT INTO HistoricoAlocacao
(Colaborador_idColaborador, Cargo_idCargo, Departamento_idDepartamento, Data_Inicio, Data_Fim, Observacao)
VALUES
(1,1,1,'2024-01-15',NULL,'Alocação inicial'),
(2,2,2,'2023-09-01',NULL,'Departamento RH'),
(3,3,3,'2022-03-10',NULL,'Controle financeiro'),
(4,4,4,'2025-01-20',NULL,'Equipe criativa'),
(5,5,5,'2021-06-11',NULL,'Suporte ao cliente');

-- =========================
-- TABELA: RegistroPonto
-- =========================
INSERT INTO RegistroPonto
(Colaborador_idColaborador, Data_Hora, Tipo, Justificativa)
VALUES
(1,'2026-05-01 08:00:00','Entrada','Entrada normal'),
(2,'2026-05-01 08:10:00','Entrada','Atraso devido trânsito'),
(3,'2026-05-01 12:00:00','Saída','Intervalo almoço'),
(4,'2026-05-01 13:00:00','Entrada','Retorno almoço'),
(5,'2026-05-01 18:00:00','Saída','Fim expediente');

-- =========================
-- TABELA: FolhaPagamento
-- =========================
INSERT INTO FolhaPagamento
(Colaborador_idColaborador, Competencia_Ano, Competencia_Mes, Salario_Bruto, Desconto_INSS, Desconto_FGTS, Desconto_IRRF, Outros_Descontos, Salario_Liquido, Data_Pagamento)
VALUES
(1,2026,5,6000,600,480,300,100,4520,'2026-05-30'),
(2,2026,5,4500,450,360,200,50,3440,'2026-05-30'),
(3,2026,5,5200,520,416,250,80,3934,'2026-05-30'),
(4,2026,5,3500,350,280,120,40,2710,'2026-05-30'),
(5,2026,5,3200,320,256,100,30,2494,'2026-05-30');

-- =========================
-- TABELA: Ferias
-- =========================
INSERT INTO Ferias
(Colaborador_idColaborador, Data_Inicio_Aquisitivo, Data_Fim_Aquisitivo, Saldo_dias, Data_Inicio_Ferias, Data_Fim_Ferias, Dias_Ferias)
VALUES
(1,'2025-01-01','2025-12-31',30,'2026-01-10','2026-02-09',30),
(2,'2025-01-01','2025-12-31',20,'2026-03-01','2026-03-20',20),
(3,'2025-01-01','2025-12-31',15,'2026-04-01','2026-04-15',15),
(4,'2025-01-01','2025-12-31',10,'2026-06-01','2026-06-10',10),
(5,'2025-01-01','2025-12-31',25,'2026-07-01','2026-07-25',25);

-- =========================
-- TABELA: Beneficio
-- =========================
INSERT INTO Beneficio (Nome, Descricao, Valor_Padrao) VALUES
('Vale Transporte','Auxílio transporte',300),
('Vale Refeição','Auxílio alimentação',600),
('Plano de Saúde','Convênio médico',800),
('Gympass','Academia',120),
('Auxílio Home Office','Internet e energia',150);

-- =========================
-- TABELA: ColaboradorBeneficio
-- =========================
INSERT INTO ColaboradorBeneficio
(Beneficio_idBeneficio, Colaborador_idColaborador, Valor_Individual, Data_Inicio, Data_Fim)
VALUES
(1,1,300,'2026-01-01',NULL),
(2,2,600,'2026-01-01',NULL),
(3,3,800,'2026-01-01',NULL),
(4,4,120,'2026-01-01',NULL),
(5,5,150,'2026-01-01',NULL);

-- =========================
-- TABELA: Desligamento
-- =========================
INSERT INTO Desligamento
(Colaborador_idColaborador, MotivoDesligamento_idMotivo, Data_Desligamento, Saldo_Salario, Ferias_Proporcionais, Decimo_Terceiro, FGTS_Rescisorio, Multa_FGTS, Total_Rescisao, Observacao)
VALUES
(1,1,'2026-05-01',2000,1000,1200,800,320,5320,'Desligamento amigável'),
(2,2,'2026-05-02',1800,900,1000,700,280,4680,'Corte de custos'),
(3,4,'2026-05-03',1500,700,800,500,200,3700,'Fim de contrato'),
(4,5,'2026-05-04',2200,1200,1300,900,360,5960,'Aposentadoria'),
(5,1,'2026-05-05',1600,800,900,600,240,4140,'Mudança de cidade');

-- =========================
-- TABELA: Ocorrencia
-- =========================
INSERT INTO Ocorrencia
(Colaborador_idColaborador, TipoOcorrencia_idTipoOcorrencia, idGestor, Data_Ocorrencia, Descricao)
VALUES
(1,1,2,'2026-05-10','Atraso recorrente'),
(2,4,1,'2026-05-11','Excelente desempenho'),
(3,2,1,'2026-05-12','Falta injustificada'),
(4,3,2,'2026-05-13','Descumprimento de normas'),
(5,4,3,'2026-05-14','Bom atendimento ao cliente');

-- =========================
-- TABELA: Vaga
-- =========================
INSERT INTO Vaga
(Cargo_idCargo, Departamento_idDepartamento, StatusdeVagas_idStatusVagas, Titulo, Data_Abertura, Data_Encerramento, Tipo)
VALUES
(1,1,1,'Desenvolvedor Java Jr','2026-05-01','2026-06-01','CLT'),
(2,2,2,'Assistente de RH','2026-05-02','2026-06-02','CLT'),
(3,3,1,'Analista Financeiro','2026-05-03','2026-06-03','PJ'),
(4,4,3,'Designer Gráfico','2026-05-04','2026-06-04','Estágio'),
(5,5,1,'Técnico de Suporte','2026-05-05','2026-06-05','CLT');

-- Consultas (Selects)

-- TABELA: Sexo
SELECT * FROM Sexo;
SELECT Desc_Sexo FROM Sexo;
SELECT * FROM Sexo WHERE idSexo = 1;
SELECT * FROM Sexo ORDER BY Desc_Sexo;
SELECT COUNT(*) FROM Sexo;

-- TABELA: EstadoCivil
SELECT * FROM EstadoCivil;
SELECT Desc_EstadoCivil FROM EstadoCivil;
SELECT * FROM EstadoCivil WHERE idEstadoCivil = 2;
SELECT * FROM EstadoCivil ORDER BY Desc_EstadoCivil;
SELECT COUNT(*) FROM EstadoCivil;

-- TABELA: Departamento
SELECT * FROM Departamento;
SELECT Nome FROM Departamento;
SELECT * FROM Departamento WHERE Sigla = 'TI';
SELECT * FROM Departamento ORDER BY Nome;
SELECT COUNT(*) FROM Departamento;

-- TABELA: Cargo
SELECT * FROM Cargo;
SELECT Titulo FROM Cargo;
SELECT * FROM Cargo WHERE Salario_Base > 4000;
SELECT * FROM Cargo ORDER BY Salario_Base DESC;
SELECT COUNT(*) FROM Cargo;

-- TABELA: Colaborador
SELECT * FROM Colaborador;
SELECT Nome, CPF FROM Colaborador;
SELECT * FROM Colaborador WHERE Status_Colaborador = 1;
SELECT * FROM Colaborador ORDER BY Nome;
SELECT COUNT(*) FROM Colaborador;

-- TABELA: Beneficio
SELECT * FROM Beneficio;
SELECT Nome FROM Beneficio;
SELECT * FROM Beneficio WHERE Valor_Padrao > 200;
SELECT * FROM Beneficio ORDER BY Nome;
SELECT COUNT(*) FROM Beneficio;

-- TABELA: Vaga
SELECT * FROM Vaga;
SELECT Titulo FROM Vaga;
SELECT * FROM Vaga WHERE Tipo = 'CLT';
SELECT * FROM Vaga ORDER BY Data_Abertura;
SELECT COUNT(*) FROM Vaga;